### ISSUE TITLE
Seeking to preserve order of keys in map after decode

### ISSUE THREAD

**Issue by dyba** [dakrone/cheshire#73]
I am retrieving a JSON template from a remote server which I will use to populate and then send back to create a record on that server. When I ```decode``` the template in the body of the response, the resulting map reorders the keys in the original template. Unfortunately, the remote server will not accept my request to create a record since I have submitted a JSON template with reordered keys.

I found a library that allows me to keep the ordered nature of the JSON template using the ```ordered-map``` function. With that find, I tried using the ```decode``` method to preserve the ordering of the keys in the JSON template by checking the root level field name and converting the associated value to an ordered map:

``` clojure
;; here (new-contribution-receipt) returns a response from the remote server containing
;; the JSON template in the body key
(decode
  (:body (new-receipt))
  false
  (fn [field-name]
    (if (= field-name "contributionReceipt")
      ordered-map
      {})))
;; => keys are not ordered
```

That didn't work, so I'm trying to think of the problem from a different angle. Perhaps I need to modify Cheshire's ```decode``` function so that I can pass an option that would let me apply a function (i.e. ```ordered-map```) to values that are maps?

Does the community have any ideas on how I can tackle this problem?

**Comment by dyba** [comment]
@dakrone I referenced the same line you quoted from the JSON spec to the third-party vendor who maintains the server. I've yet to hear back from them if they are able to change it.

**Comment by jayp** [comment]
HI @dakrone - I appreciate software that allow for a more liberal interpretation of standards. For instance, web browsers attempt to follow the standard, but are forgiving. With that said, it's your call. No sleep lost if this issue were closed without any affect.

**Comment by dyba** [comment]
@jayp @dakrone I just got a response from the third-party. They are indeed using an XML generator under the hood to generate their JSON, which explains why they require any JSON templates in a request sent to them to be ordered.

I think the workaround would be to use their API and request the data as XML rather than JSON. Thank you both for taking the time to read my issue and provide your feedback. :+1:

**Comment by px0** [comment]
FWIW I just ran into this as well. I really think this should be an option. Sometimes APIs are just wrong but we still have to deal with it.

**Comment by px0** [comment]
If anyone else needs this, here is a fork that includes the `map-coerce-fn` as described by @jayp : https://github.com/px0/cheshire

**Comment by ivos** [comment]
Another use case: I want to test a REST API I am building. In the tests I want to verify the whole JSON response body by matching it as a String to the content of a JSON file with expected response body. In order to prevent whitespace-related issues when comparing the Strings I need to re-format both the expected and actual JSONs using the same formatter. In case of mismatch I also want to be able to replace the template file content with the actual response, obviously without re-ordering the fields of large maps/objects.

Doing this in plain Java using Jackson works OK (using `TreeNode` as the intermediary data structure and `.readTree` and `.writeTree` methods).

Would be great to be able to use Cheshire for this on a Clojure project.

Also, I'd like to point out that although the JSON standard might not **guarantee** the order of map keys, all JSON processing libraries I know of **do keep it**, including Javascript's own `JSON.parse`, and Java's Jackson which is used by Cheshire.

The different order of the keys is **NOT because of** JSON as the resolution might imply. The reason is the way Clojure manages map datastructures, as already pointed out by @ztellman above, and that has nothing to do with JSON itself.

I would therefore dare to propose not only to open this feature to extensibility (although even this would be great), but to consider using `ordered-map` by default. This would make Cheshire consistent with all other JSON libraries out there.

I would prefer consistency over trying to minimize memory overhead, which is not quantified anyway, I know these are just my personal priorities, but extensibility would allow for more efficient datastructure (like Clojure's `{}`), should the user so desire.

**Comment by JulesGosnell** [comment]
I need to load json docs and preserve order of keys aswell - seems to me that if you provide an API for overriding implementation of "array" (defaulting to vector) you should do the same for impl of "object" (defaulting to hash-map).

I might want to load directly into a sorted-map, to save sorting later...
I might want to load into custom record types....
I might want to preserve key order in spite of json spec...
I might want to...

Jules

**Comment by JulesGosnell** [comment]
I was reviewing our project's having to have it's own copy of `cheshire-parse.clj` just to hack it to allow the overriding of a custom map type for all json-objects.

I thought I had given pretty good reasons above as to why this would be a useful and sensible addition to the API but I see that two releases of Cheshire have been done this year and neither appears to include this feature :-( Perhaps we needed to shout louder to get it in ?

- it nicely complements the similar `array-coerce-fn`
- most of a json doc is made of json objects, it is not unlikely that I might have my own impl
- as long as my impl supports map and transient/persistent interfaces (which it does) it is a trivial change
- there seem to be a number of people asking for it
- a library should allow the user to extend it to fit snugly into their usecase - this is real pain-point in my use of cheshire

I would really appreciate it if this feature could be considered for the next release.

many thanks

Jules

**Comment by mtrimpe** [comment]
Another use-case for which I needed ordered keys is consistently serializing JSON to allow for hash-based comparisons on the generated string.

Since consumers must be able to do these comparisons as well they need to work on the serialized string and can't be based on the internal Clojure data structure.

If there is a JSON schema for the JSON then this can be achieved always serialize properties in the order defined in the associated JSON schema.

That only works if the JSON schema can first be read the provided order and then have the output serialized against that order.

**Comment by Iddodo** [comment]
How are you handling the absence of this feature nowadays? Is there a solution?

I needed to edit some JSON for a code review, and the lack of order in keys makes the diff comparison very much unreadable, so that might be another use-case (albeit admittedly quite the trivial one).

**Comment by borkdude** [comment]
A (hacky?) alternative solution is to use clj-yaml which supports ordered maps:

```
bb -e '(-> (clj-yaml.core/parse-string "{\"a\": 1, \"b\": 2, \"c\": 2, \"d\": 2, \"e\": 2, \"f\": 2, \"g\": 2, \"i\": 2}") (assoc :a 2) (cheshire.core/generate-string))'
"{\"a\":2,\"b\":2,\"c\":2,\"d\":2,\"e\":2,\"f\":2,\"g\":2,\"i\":2}"
```

if you replace `clj-yaml.core/parse-string` with `cheshire.core/parse-string`  the order _will_ change, but when reading it as yaml, the order is preserved. FWIW.
