### ISSUE TITLE
URL decoding certain fields?

### ISSUE THREAD

**Issue by didibus** [dakrone/cheshire#91]
Hi,

I'm dealing with some JSON which contains some URL encoded fields, and I wonder if there's a way you can setup a custom decoder for some fields where I could specify how to decode the URL.

Thank you.

**Comment by gfredericks** [comment]
I don't think cheshire has anything like that, and I'm curious what the value would be to you versus doing the transformation yourself after cheshire parses it -- is it the low-level performance aspect of not having to make new data structures, or is it just about how the code is written?

**Comment by didibus** [comment]
In my case it's more about the code. I'm currently decoding the field after the fact. In terms of organisation, I would find it cleaner if I could configure this behavior as part of Cheshire itself.

I was mostly curious, since we have custom encoders, technically I could use Cheshire to encode certain fields and have it do the url encoding as part of a custom encoder. Unless I'm misunderstanding custom encoders, wouldn't the reverse operation be a nice feature to have?

**Comment by gfredericks** [comment]
It's just harder -- custom encoders can be type-based, whereas for decoding, asking for all strings to be treated a certain way wouldn't be very useful, and decoding based on the name of the field is sloppy (since the same name can appear in different contexts and mean different things).

I have some ideas for handling this problem in a nicer way, but they'd take a lot of work and are probably outside the scope of cheshire.

**Comment by didibus** [comment]
I see the extra challenges. I'll make due with decoding it myself after the fact.
Thanks.

**Comment by gfredericks** [comment]
as a followup I should point to [this](https://github.com/gfredericks/schema-bijections) library I created for use with the [schema library](https://github.com/Prismatic/schema) to solve these kinds of problems.
