### ISSUE TITLE
Parsing timestamps

### ISSUE THREAD

**Issue by danielcompton** [dakrone/cheshire#93]
I've seen the docs on encoding timestamps as JSON strings, is there the capability to go in the reverse direction, i.e. to parse `"2015-12-06T18:41:51.578051264Z"` as a (preferably) java.time.Instant?

It looks like https://github.com/FasterXML/jackson-datatype-jsr310 might be helpful for this?

**Comment by gfredericks** [comment]
I don't think there's any clean solution for inferring the desired host type for something parsed from JSON (which is one of the complaints that [transit](https://github.com/cognitect/transit-format#rationale) makes), since without any sort of schema the task is fundamentally ambiguous.

This of course means that libraries like cheshire are highly asymmetric, with good support for customizing encoding based on host type and virtually no support for doing the inverse.

This asymmetry has bothered me a lot too, and I eventually developed an approach using the [prismatic/schema](https://github.com/Prismatic/schema) library that I think addresses the problem. The library is [here](https://github.com/gfredericks/schema-bijections) if you're interested.

**Comment by dakrone** [comment]
I agree with @gfredericks about there not being a good clean solution for this. I also think this is out of scope for a library like Cheshire. Looks like there is already a library for it, so I'm going to close this issue.
